make hlut widget optional
fastplotlib/fastplotlib pull request #351
Opened 2023-10-31 19:59 UTC by clewis7

2023-10-31 20:08 UTC, clewis7 commented
would be nice to add an hlut button to the toolbar so it can be generated after imagewidget instantiation if a user wanted one for a specific subplot!

2023-10-31 21:37 UTC, kushalkolar requested changes

2023-10-31 21:37 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +            determines whether each subplot is rendered with a Histogram LUT widget
More concise: make histogram LUT widget for each image?

2023-10-31 21:38 UTC, kushalkolar commented
> would be nice to add an hlut button to the toolbar so it can be generated after imagewidget instantiation if a user wanted one for a specific subplot!

I think this is feature creep, we they can create and add it programmatically if they need that level of customization?

2023-11-01 04:41 UTC, kushalkolar commented
Also add kwarg to specify subsample dims for HistogramLut widget?

2023-11-01 04:54 UTC, kushalkolar commented on fastplotlib/widgets/image.py
> +        histogram_widget: bool = False,
I think default should be `True` :D

2023-11-01 14:22 UTC, clewis7 commented on fastplotlib/widgets/image.py
> +        histogram_widget: bool = False,
```suggestion
        histogram_widget: bool = True,
```

2023-11-01 14:22 UTC, clewis7 commented on fastplotlib/widgets/image.py
> +            determines whether each subplot is rendered with a Histogram LUT widget
```suggestion
            make histogram LUT widget for each subplot
```

2023-11-01 17:49 UTC, kushalkolar commented
> > Also add kwarg to specify subsample dims for HistogramLut widget?
> 
> @kushalkolar anything more than number of bins? or you want a dict that allows user to pass nbins and flank?

Just a tuple of its to specify the max size?

2023-11-03 04:08 UTC, kushalkolar commented
going to merge this, see #359 for the subsample

2023-11-03 04:52 UTC, merged