add lorenz attractor example
fastplotlib/fastplotlib pull request #595
Opened 2024-08-26 16:55 UTC by clewis7

Had way too much fun doing this :D 

https://github.com/user-attachments/assets/b37da96b-3615-402f-86cb-4036e141f7a3

2024-08-26 16:58 UTC, kushalkolar commented
@jpughesanford your fav thing to plot 😁

2024-08-31 13:26 UTC, kushalkolar requested changes

2024-08-31 13:26 UTC, kushalkolar commented on examples/desktop/misc/lorenz_animation.py
> +Example the Lorenz attractor.
of

2024-08-31 13:26 UTC, kushalkolar commented on examples/desktop/misc/lorenz_animation.py
> +lorenz_data = list()
preallocate an array to account for the 3,000 timesteps instead of appending to a list?

2024-08-31 13:26 UTC, kushalkolar commented on examples/desktop/misc/lorenz_animation.py
> +    marker = figure[0, 0].add_scatter(graphic.data.value[0], sizes=8)
use color from the corresponding line?

2024-08-31 13:28 UTC, kushalkolar commented
mostly LGTM! Few minor comments

I think it would be nice to also have another example that visualizes it in this way: https://en.wikipedia.org/wiki/File:A_Lorenz_system.ogv 

Maybe using a rolling buffer to show the most recent n_timepoints?

2024-09-01 15:12 UTC, clewis7 commented
>I think it would be nice to also have another example that visualizes it in this way: https://en.wikipedia.org/wiki/File:A_Lorenz_system.ogv

@kushalkolar this would be cool, I can work on some time this coming week

2024-09-01 17:21 UTC, kushalkolar approved these changes

2024-09-01 17:21 UTC, merged