update contrib guide, add developer notes
fastplotlib/fastplotlib pull request #667
Opened 2024-10-24 15:28 UTC by clewis7

supersedes #580

Because something wonky happened with the iris dataset and all of the changes with imgui, it was easier to just open a new PR for this

2024-10-24 16:30 UTC, kushalkolar commented
Some formatting issues and also add the developer docs as a separate dir, like user guide, and have a toc page with the graphics and plotarea in the toctree

2024-10-25 16:08 UTC, kushalkolar requested changes

2024-10-25 16:08 UTC, kushalkolar commented on docs/source/developer_notes/graphics.rst
> +ex: ``line_graphics.colors[bool_array] = "red"``
You can use the unicode emoji instead: 😄

In KDE Plasma you can get the emoji selector from the app menu

2024-10-25 17:24 UTC, clewis7 commented on docs/source/developer_notes/graphics.rst
> +ex: ``line_graphics.colors[bool_array] = "red"``
```suggestion
ex: ``line_graphics.colors[bool_array] = "red"`` 😊
```

2024-10-25 18:58 UTC, kushalkolar requested changes

2024-10-25 18:58 UTC, kushalkolar commented on CONTRIBUTING.md
> +graphics or selector tools), bug fixes, or the addition of new examples to the [examples gallery](https://fastplotlib.readthedocs.io/en/latest/_gallery/index.html).
update link to our new domain and /ver/dev

2024-10-25 18:58 UTC, kushalkolar commented on CONTRIBUTING.md
> +[`For Develeopers`](https://fastplotlib.readthedocs.io/en/latest/developer_notes/index.html) section of the package documentation.
update link to our new domain and /ver/dev

2024-10-25 21:15 UTC, clewis7 commented on CONTRIBUTING.md
> +graphics or selector tools), bug fixes, or the addition of new examples to the [examples gallery](https://fastplotlib.readthedocs.io/en/latest/_gallery/index.html).
```suggestion
graphics or selector tools), bug fixes, or the addition of new examples to the [examples gallery](https://www.fastplotlib.org/ver/dev/). 
```

2024-10-25 21:16 UTC, clewis7 commented on CONTRIBUTING.md
> +[`For Develeopers`](https://fastplotlib.readthedocs.io/en/latest/developer_notes/index.html) section of the package documentation.
```suggestion
[`For Develeopers`](https://www.fastplotlib.org/ver/dev/developer_notes/index.html) section of the package documentation.
```

2024-10-25 21:23 UTC, kushalkolar approved these changes

2024-10-25 21:28 UTC, merged